[package]
name = "clean_gmail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.23.27"
rustls-pemfile = "2.2.0"
webpki-roots = "1.0.0"
